# `OperationResult<TValue>`

A structure for representing an operation result with a success or failure status, containing a `TValue` in cases of success or a collection of errors in cases of failure.

The `OperationResult<TValue>` is similar to the `OperationResult`, but has a value when successful.

The following demonstrates how to use the `OperationResult<TValue>` struct.

## Creating a success result

The examples below show how to create a successful result:

```csharp
// create the value
var product = new Product("Product name", 10.0m);

// create the success result from the value
var result = new OperationResult<Product>(product);

// or
OperationResult<Product> result = new(product);
```

It is also possible to create using implicit conversion:

```csharp
// create the value
var product = new Product("Product name", 10.0m);

// create the success result from the value
OperationResult<Product> result = product;
```

Se o retorno do método for um `OperationResult<TValue>`, você pode retornar o valor diretamente:

```csharp
public OperationResult<Product> CreateSuccessSample()
{
    // create the value
    var product = new Product("Product name", 10.0m);

    // return the value directly, the implicit conversion will create the success result
    return product;
}
```

## Creating a failure result

Failure results follow the same operation as `OperationResult`.

The sample below shows how to create a failure result:

```csharp
var errors = new ResultErrors();
errors += ResultMessage.Error("Error message");

var result = new OperationResult<Product>(errors);
```

You can create the `OperationResult<TValue>` using the implicit conversion from `ResultErrors` to `OperationResult<TValue>`:

```csharp
var errors = new ResultErrors();
errors += ResultMessage.Error("Error message");

OperationResult<Product> result = errors;
```

There is also an implicit conversion from the error message:

```csharp
OperationResult<Product> result = ResultMessage.Error("Error message");
```

Once a successful `OperationResult<TValue>` has been created, it is not possible to add errors to it.
If you try to add errors to a successful `OperationResult<TValue>`, an exception will be thrown.

If you want to perform validations and return an `OperationResult<TValue>` of success or failure, you can do so as follows:

```csharp
public OperationResult<Product> CreateFailureOrSuccessSample(string name, decimal price)
{
    if (string.IsNullOrWhiteSpace(name))
    {
        return ResultMessage.Error("Name is required");
    }

    if (price <= 0)
    {
        return ResultMessage.Error("Price must be greater than zero");
    }

    return new Product(name, price);
}
```

Another way is to create a `ValidableResult`, check for errors, and return the errors or the value object. See below:

```csharp
public OperationResult<Product> ValidateAndCreateFailureOrSuccessSample(string name, decimal price)
{
    ValidableResult validation = new();
    
    if (string.IsNullOrWhiteSpace(name))
        validation += ResultMessage.Error("Name is required");

    if (price <= 0)
        validation += ResultMessage.Error("Price must be greater than zero");

    if (validation.TryGetError(out var error))
        return error;


    return new Product(name, price);
}
```

## Working with the `OperationResult<TValue>`

The `OperationResult<TValue>` has the same methods as the `OperationResult`, and some additional methods to work with the value.

These are the methods available for `OperationResult`:

- `TryGetError`
- `Convert`
- `Match`
- `TryConvertError<TOtherError>`
- `IsSuccessOrGetError`
- `IsSuccessOrConvertError`

The following additional methods are available for `OperationResult<TValue>`:

- `TryGetValue`
- `TryConvertValue`
- `IsFailureOrGetValue`
- `IsFailureOrConvertValue`
- `IsFailureAndGet`
- `IsSuccessAndGet`

Now let's just look at the additional methods. The other methods have already been covered in the previous session, but the `Match` method will be covered again, as it has a different overload.

### `TryGetValue`

This method checks whether the result is a success, returning true if it is and the value. If the result is a failure, it returns false and the value null.

Here's an example:

```csharp
OperationResult<Product> result = Create("Product 1", 10.5m);

if (result.TryGetValue(out var product))
{
    DoSomething(product);
}
```

### `TryConvertValue`

This method is similar to `TryGetValue`, returning a `bool`, being true when the result is a success. However, instead of the output being a `TValue`, it will be the result of converting the `TValue` into a `TOtherValue`.

The conversion will only take place if the result is a success.

Here's an example of how to use it:

```csharp
OperationResult<Product> result = Create("Product 1", 10.5m);

if (result.TryConvertValue(static product => product.Name, out var name))
{
    DoSomething(name);
}
```

There is an overload of the method, which can receive an additional parameter that will be used in the conversion function:

```csharp
public TOtherValue? TryConvertValueSample<TOtherValue>(ISelector<Product, TOtherValue> selector)
    where TOtherValue : class
{
    OperationResult<Product> result = Create("Product 1", 10.5m);

    if (result.TryConvertValue(selector, static (p, s) => s.Select(p), out TOtherValue? other))
    {
        return other;
    }

    return default;
}
```

### `IsFailureOrGetValue`

This method checks whether the result is a failure, returning true if it is and the value null. If the result is a success, it returns false and the value.

This method is similar to `TryGetValue`, however the check is inverted, assigning the value if the method returns false.

You can use for something like this:

```csharp
public OperationResult IsFailureOrGetValueSample()
{
    OperationResult<Product> result = Create("Product 1", 10.5m);

    if (result.IsFailureOrGetValue(out var product))
    {
        // if the result is a failure,
        // the return will be true and the value null
        return result;
    }

    var otherResult = DoSomethingElse(product);

    return otherResult;
}
```

### `IsFailureOrConvertValue`

This method is similar to `TryConvertValue`, returning a `bool`, being true when the result is a failure. However, instead of the output being a `TValue`, it will be the result of converting the `TValue` into a `TOtherValue`.

The conversion will only take place if the result is a failure.

Here's an example of how to use it:

```csharp
public OperationResult IsFailureOrConvertValueSample()
{
    OperationResult<Product> result = Create("Product 1", 10.5m);

    if (result.IsFailureOrConvertValue(static product => product.Name, out var name))
    {
        return result;
    }

    DoSomething(name);

    return new();
}
```

### `IsFailureAndGet`

This method will check if the result is a failure, returning true if it is and the errors. If the result is a success, if will return false and the value.

Here's an example:

```csharp
public OperationResult<TOtherValue> IsFailureAndGetSample<TOtherValue>()
{
    OperationResult<Product> result = Create("Product 1", 10.5m);

    if (result.IsFailureAndGet(out var errors, out var product))
    {
        // if the result is failure, the errors are returned
        return errors;
    }

    // if the result is success, the value is returned
    // now you can do something with the value
    TOtherValue otherValue = DoOtherThing<TOtherValue>(product);
    return otherValue;
}
```

### `IsSuccessAndGet`

This method is similar to `IsFailureAndGet`, but the check is inverted, returning true if the result is a success and the value. If the result is a failure, it returns false and the errors.

Here's an example:

```csharp
public OperationResult<TOtherValue> IsSuccessAndGet_Sample<TOtherValue>()
{
    OperationResult<Product> result = Create("Product 1", 10.5m);

    if (result.IsSuccessAndGet(out var product, out var errors))
    {
        // if the result is success, the value is returned
        // now you can do something with the value
        TOtherValue otherValue = DoOtherThing<TOtherValue>(product);
        return otherValue;
    }

    // if the result is failure, the errors are returned
    return errors;
}
```
